### ISSUE TITLE
Column formating is off 

### ISSUE THREAD

**Issue by ttomsia** [qchrisd/LOreal-ColorshotAutomation#6] opened 2023-03-27 13:50 UTC
In the 1.01 the column formatting and colors got a little messed up.  I think everything got pushed over 1 because of the date that was added

**Comment by qchrisd** [comment] 2023-03-27 14:04
Duplicate of #5. This was indeed caused by PR #4. I will be working on a solution to make sure this is generic for v1.0.2

**Closed as completed** 2023-03-27 16:07 UTC
